# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a675f9dd9e4105a414ee7f91201ef2e40b7b4b628619471d9096f73afda18c1618c558d90815d9a3680531cbce1258e19f4d55a2fb195f36346c2a37b021b9af

test:
  secret_key_base: 31fe1752834dc6ab347311dc058a6c1ac069a10e99114ef981c797966ad3f8f9f21e47e846286583a02ebda18e651def879490c1a08573e4a7c5b13f638afc26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
